export enum EventTopic {
  COMMUNITY_POST_CREATED = 'community.post.created',
  COMMUNITY_POST_UPDATED = 'community.post.updated',
  COMMUNITY_POST_DELETED = 'community.post.deleted',
  COMMUNITY_COMMENT_CREATED = 'community.comment.created',
  COMMUNITY_COMMENT_UPDATED = 'community.comment.updated',
  COMMUNITY_COMMENT_DELETED = 'community.comment.deleted',
  COMMUNITY_REPLY_CREATED = 'community.reply.created',
  COMMUNITY_REACTION_CREATED = 'community.reaction.created',
  COMMUNITY_REACTION_UPDATED = 'community.reaction.updated',
  COMMUNITY_BOOKMARK_CREATED = 'community.bookmark.created',
  COMMUNITY_MENTION_CREATED = 'community.mention.created',
  CIVIC_ISSUE_CREATED = 'civic.issue.created',
  CIVIC_ISSUE_UPDATED = 'civic.issue.updated',
  CIVIC_ISSUE_VERIFIED = 'civic.issue.verified',
  CIVIC_ISSUE_ASSIGNED = 'civic.issue.assigned',
  CIVIC_ISSUE_IN_PROGRESS = 'civic.issue.in_progress',
  CIVIC_ISSUE_RESOLVED = 'civic.issue.resolved',
  CIVIC_ISSUE_CLOSED = 'civic.issue.closed',
  CIVIC_ISSUE_SUPPORTED = 'civic.issue.supported',
  CIVIC_ISSUE_DUPLICATE_MARKED = 'civic.issue.duplicate.marked',
  CIVIC_ISSUE_OFFICIAL_RESPONSE = 'civic.issue.official.response',
  CIVIC_ISSUE_UPDATE_CREATED = 'civic.issue.update.created',
  COMMUNITIES_CREATED = 'communities.created',
  COMMUNITIES_UPDATED = 'communities.updated',
  COMMUNITIES_MEMBER_JOINED = 'communities.member.joined',
  ORGANIZATIONS_CREATED = 'organizations.created',
  ORGANIZATIONS_VERIFIED = 'organizations.verified',
  VOLUNTEER_CAMPAIGN_CREATED = 'volunteer.campaign.created',
  VOLUNTEER_CAMPAIGN_UPDATED = 'volunteer.campaign.updated',
  VOLUNTEER_REGISTERED = 'volunteer.registered',
  VOLUNTEER_REGISTRATION_UPDATED = 'volunteer.registration.updated',
  VOLUNTEER_TASK_CREATED = 'volunteer.task.created',
  VOLUNTEER_TASK_UPDATED = 'volunteer.task.updated',
  VOLUNTEER_HOUR_RECORDED = 'volunteer.hour.recorded',
  EVENT_CREATED = 'event.created',
  EVENT_UPDATED = 'event.updated',
  EVENT_PUBLISHED = 'event.published',
  EVENT_REGISTRATION_OPENED = 'event.registration.opened',
  EVENT_REGISTRATION_CLOSED = 'event.registration.closed',
  EVENT_LIVE = 'event.live',
  EVENT_COMPLETED = 'event.completed',
  EVENT_CANCELLED = 'event.cancelled',
  EVENT_SCHEDULE_UPDATED = 'event.schedule.updated',
  EVENT_ANNOUNCEMENT_CREATED = 'event.announcement.created',
  EVENT_REGISTRATION_CREATED = 'event.registration.created',
  EVENT_REGISTRATION_CANCELLED = 'event.registration.cancelled',
  EVENT_ATTENDEE_CHECKED_IN = 'event.attendee.checked_in',
  EVENT_ATTENDEE_CHECKED_OUT = 'event.attendee.checked_out',
}
export interface DomainEvent<T = any> {
  id: string;
  topic: EventTopic;
  timestamp: Date;
  payload: T;
}
