export enum Role {
  USER = 'USER',
  ADMIN = 'ADMIN',
  MODERATOR = 'MODERATOR',
  SUPER_ADMIN = 'SUPER_ADMIN',
  GOV_ADMIN = 'GOV_ADMIN',
  DEPT_HEAD = 'DEPT_HEAD',
  SUPERVISOR = 'SUPERVISOR',
  OFFICER = 'OFFICER',
  INSPECTOR = 'INSPECTOR',
}

export enum Permission {
  // User permissions
  MANAGE_PROFILE = 'MANAGE_PROFILE',
  
  // Civic Issues
  CREATE_ISSUE = 'CREATE_ISSUE',
  UPDATE_ISSUE = 'UPDATE_ISSUE',
  DELETE_ISSUE = 'DELETE_ISSUE',
  VOTE_ISSUE = 'VOTE_ISSUE',
  
  // Admin permissions
  MANAGE_USERS = 'MANAGE_USERS',
  MANAGE_ROLES = 'MANAGE_ROLES',
  VIEW_AUDIT_LOGS = 'VIEW_AUDIT_LOGS',
}
